version: '3.8'

services:
  deps:
    image: node:18-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install --frozen-lockfile"

  app:
    container_name: gdggye-app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - deps